#include "node.h"
#include "typedef.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

NODE* nodemk(ND_TYPE type, char* data, NODE* left, NODE* right) {
  NODE* nd = (NODE* ) malloc(sizeof(NODE));

  nd->type  = type;
  nd->left  = left;
  nd->right = right;
  strncpy(nd->data, data, DATA_SZ);

  return nd;
}

char* node_get_type(NODE* token) {
  char* dest = malloc(DATA_SZ);
  #define s(str) strncpy(dest, str, DATA_SZ - 1)

  switch (token->type) {
    case ND_NULL: s("TK_NULL"); break;
    case ND_ADD:  s("ND_ADD");  break;
    case ND_SUB:  s("ND_SUB");  break;
    case ND_MUL:  s("ND_MUL");  break;
    case ND_DIV:  s("ND_DIV");  break;
    case ND_INT:  s("ND_INT");  break;

    default: s("UNKNOWN"); break;
  }

  #undef s
  return dest;
}

// I kind of blanked and decided to try this child thing
// it works, so I'm not complaining
static void traverse(NODE* node, u64* i, FILE* stream) {
  u64 child = *i;

  if (node->left) {
    traverse(node->left, i, stream);
    child = *i-1;
  }
  if (node->right) {
    traverse(node->right, i, stream);
  }

  fprintf(stream, "\n");
  if (*i == child) {
    fprintf(stream, "  // Leaf node\n");
  }
  fprintf(stream, "  nd%06lu [label=\"%s\"];\n",
  *i, node->data);

  // TODO: eliminate if statements perhaps
  if (*i != child) {
    if (node->right) {
      fprintf(stream, "  nd%06lu -- nd%06lu;\n", *i, *i-1);
    }

    if (node->left) {
      fprintf(stream, "  nd%06lu -- nd%06lu;\n", *i, child);
    }
  }

  *i += 1;
}

void nodegviz(NODE* root, FILE* stream) {
  u64 i = 0;
  fprintf(stream, "graph \"AST\" {\n");
  fprintf(stream, "  // Generated by 'nodegviz'");

  traverse(root, &i, stream);

  fprintf(stream, "}\n");
}

void nodefree(NODE* node) {
  if (node->left) {
    nodefree(node->left);
  }
  if (node->right) {
    nodefree(node->right); 
  }

  free(node);
}
